import type { Metadata } from "next";
import { AR_One_Sans, Poppins } from "next/font/google";
import "./globals.css";

const arOneSans = AR_One_Sans({
  variable: "--font-ar-one-sans",
  subsets: ["latin"],
  weight: "variable",
  display: "swap",
});

const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700'],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${arOneSans.variable} ${poppins.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
